About Page
INIT-Build-Web-Dev-3-Spring-2024/init-website pull request #11
Opened 2024-03-09 00:14 UTC by ERivas-786

-Migrated about page to support NextJS and its new features
-Implemented API routing and calls to eventually be used with Notion and Databases
-Organized folder structure
-Possible merge conflict for middleware.ts file as well as next.config.js

2024-03-10 15:36 UTC, 02danieljonas commented
You should not use the head component in app directory: [next documentation](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#metadata)

2024-03-10 15:39 UTC, 02danieljonas requested changes

2024-03-10 15:39 UTC, 02danieljonas commented on src/app/about/page.tsx
> +        <Head>
You should not use the head component in app directory: [next documentation](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#metadata)

2024-03-10 15:54 UTC, 02danieljonas commented on src/app/about/page.tsx
> +                style={{ width: "100%" }}
nitpicky but you can do width={"100%"} instead of using the style attribute

2024-03-10 16:37 UTC, 02danieljonas requested changes

2024-03-10 16:37 UTC, 02danieljonas commented on src/app/about/page.tsx
> +            src="/Empowering_tech_talent.jpg"
Not the correct path to the image, correct path is: /images/eboard/Empowering_tech_talent.jpg

2024-03-10 16:37 UTC, 02danieljonas commented on src/app/about/page.tsx
> +      <section className="mx-auto max-w-screen-lg ">
A \<section> tag does not make sense here, since this is the main content of the page, it should be a \<main> tag instead.

2024-03-10 16:58 UTC, 02danieljonas commented on src/app/about/Chapter_card.tsx
> +        <Image src={image} alt="Chapter Logo" width={300} height={300} />
I think alt attribute should be similar to the ones in Init_Team.tsx: alt={`${name} Chapter Logo`}

2024-03-12 21:54 UTC, styled-man requested changes

2024-03-12 21:54 UTC, styled-man commented on public/images/logos/next.svg
This file is empty, delete it if not needed

2024-03-12 21:54 UTC, styled-man commented on public/images/logos/vercel.svg
This file is empty, delete it if not needed

2024-03-12 21:54 UTC, styled-man commented on src/app/about/page.tsx
> +        </Head> */}
If not necessary, please delete

2024-03-12 21:54 UTC, styled-man commented on src/app/about/page.tsx
> +import Head from "next/head";
Not being used

2024-04-03 12:41 UTC, closed without merging