Program
INIT-Build-Web-Dev-3-Spring-2024/init-website pull request #13
Opened 2024-03-18 02:37 UTC by PoojaLad55

Migrated programs page

2024-03-19 15:39 UTC, 02danieljonas requested changes

2024-03-19 15:39 UTC, 02danieljonas commented on src/app/programs/page.tsx
> +      <div className="grid grid-cols-3 gap-6 lg:grid-cols-4">
On smaller displays, the grid should only have one column: `sm:grid-cols-1 md:grid-cols-3`

2024-03-19 15:39 UTC, 02danieljonas commented on src/app/programs/programCard.tsx
> +            </svg>
You can add the SVG to a separate file for a cleaner finish: 
https://github.com/INIT-Build-Web-Dev-3-Spring-2024/init-website/blob/b712030bc40b4e0259ac07227f0f579b65846980/src/components/Navbar.tsx#L9
https://github.com/INIT-Build-Web-Dev-3-Spring-2024/init-website/blob/b712030bc40b4e0259ac07227f0f579b65846980/src/components/Navbar.tsx#L63
[InitLogo](https://github.com/INIT-Build-Web-Dev-3-Spring-2024/init-website/blob/b712030bc40b4e0259ac07227f0f579b65846980/public/assets/images/logo.svg)

2024-03-19 15:39 UTC, 02danieljonas commented on src/app/api/programs/route.ts
> +    },
You modified these description to work best within your code.

2024-03-19 15:39 UTC, 02danieljonas commented on src/app/api/programs/route.ts
> +    },
You did not modify these descriptions and the output looks like: `INIT Discover is a program focused on INIT Discover is a program focused...`

2024-03-19 15:39 UTC, 02danieljonas commented on src/app/api/programs/route.ts
If you have to modify the description, you can remove the `INIT Explore` but keep the `is a program focused on`, so it is not static within your code: 
https://github.com/INIT-Build-Web-Dev-3-Spring-2024/init-website/blob/11a055b88de5e44da568d3c42fc7ccfbe37bb854/src/app/programs/programCard.tsx#L47-L48

2024-03-19 15:44 UTC, styled-man requested changes

2024-03-19 15:44 UTC, styled-man commented on src/app/programs/page.tsx
> +  const programRequest = await fetch("http://localhost:3000/api/programs");
This being hardcoded will give an error when someone is not running the app on localhost:3000.

Use this solution from the job branch that uses a [middleware.ts](https://github.com/INIT-Build-Web-Dev-3-Spring-2024/init-website/blob/job/src/middleware.ts) file and a [dynamic fetch url](https://github.com/INIT-Build-Web-Dev-3-Spring-2024/init-website/blob/c60f88c375cfbef65849c73900df69094882fb3d/src/app/jobs/%40companies/page.tsx#L12)

2024-03-26 22:49 UTC, styled-man approved these changes

2024-03-28 20:31 UTC, styled-man approved these changes

2024-03-28 20:33 UTC, KGCarol approved these changes

2024-03-28 20:35 UTC, 02danieljonas approved these changes
LGTM!

2024-03-28 20:36 UTC, merged