Signup signin
INIT-Build-Web-Dev-3-Spring-2024/init-website pull request #14
Opened 2024-03-19 23:00 UTC by WriteCodeRAM

[](Working on using authJS [universal auth](https://authjs.dev/guides/upgrade-to-v5) instead

2024-03-21 16:52 UTC, styled-man requested changes

2024-03-21 16:52 UTC, styled-man commented on src/middleware.ts
I don't think this is necessary

2024-03-21 16:52 UTC, styled-man commented on src/app/api/auth/[...nextauth]/options.ts
Format this to get rid of the weird spacing

1. Right Click
2. Format Document

<img width="314" alt="image" src="https://github.com/INIT-Build-Web-Dev-3-Spring-2024/init-website/assets/55722176/a95b2e62-ee1a-4a25-be71-b5a320691eac">

2024-03-21 16:52 UTC, styled-man commented on src/app/page.tsx
> +
I don't think this does anything

2024-03-21 17:24 UTC, WriteCodeRAM commented on src/app/page.tsx
> +
Left it in there from main.

2024-03-22 22:57 UTC, 02danieljonas commented
LGTM!

2024-03-22 23:04 UTC, 02danieljonas submitted a review, later dismissed
LGTM!!

2024-03-22 23:13 UTC, 02danieljonas approved these changes

2024-03-26 21:10 UTC, styled-man approved these changes

2024-03-26 21:11 UTC, styled-man approved these changes

2024-03-26 21:11 UTC, merged