Events
INIT-Build-Web-Dev-3-Spring-2024/init-website pull request #15
Opened 2024-03-22 21:46 UTC by rafaelcestti

Migrated events page & dynamically add events from a Notion database.

Notion database is based off of this notion, https://smyvens.notion.site/b1c5ddd386bb4abcaab264d630246d99?v=d340036c928e40bea2ac68c41c3d5461

with three additional properties, "Description" text property, "Luma" link property, and "Picture" file property

2024-03-22 22:20 UTC, WriteCodeRAM approved these changes

2024-03-26 21:32 UTC, styled-man requested changes

2024-03-26 21:32 UTC, styled-man commented on src/components/Button.tsx
> +  buttonText: string;
rename to `children` so it can be used like this `<Button>what ever text I want to go inside</Button>`

2024-03-26 22:14 UTC, WriteCodeRAM approved these changes

2024-03-26 22:19 UTC, styled-man approved these changes

2024-03-26 22:19 UTC, merged