Jobs
INIT-Build-Web-Dev-3-Spring-2024/init-website pull request #16
Opened 2024-03-22 21:50 UTC by DimitriPL5

**DETAILS**
- Migrated the jobs page. 
- Connected to the DB to pull job data. 
- Added functionality for searching and filtering jobs. 

**To Do**
- Styling. 
- Allow for a search and filter to be done at the same time. 
- Clarify if group by companies will be on the new site (Additional work needed here if it will be included).

**TESTING**
with 'npm run dev'.

2024-03-29 22:56 UTC, styled-man requested changes

2024-03-29 22:56 UTC, styled-man commented on src/interfaces/Search.interface.ts
This is being imported in one file, can we just define it in there

2024-03-29 22:56 UTC, styled-man commented on src/app/jobs/JobModal.tsx
This file is not used anywhere, I think it safe to be deleted

2024-03-29 22:56 UTC, styled-man commented on src/Data/programData.ts
This file is not used anywhere, I think it safe to be deleted

2024-03-29 22:56 UTC, styled-man commented on src/Data/InitTeam.ts
This file is not used anywhere, I think it safe to be deleted

2024-03-29 22:56 UTC, styled-man commented on src/Data/chapters.ts
This file is not used anywhere, I think it safe to be deleted

2024-03-29 22:56 UTC, styled-man commented on src/Data/eventsData.ts
This file is not used anywhere, I think it safe to be deleted

2024-03-29 22:56 UTC, styled-man commented on src/Data/jobPostingsData.ts
This file is not used anywhere, I think it safe to be deleted

2024-03-29 22:56 UTC, styled-man commented on src/app/api/jobRoutes.ts
I don't think this file has any functionality

2024-03-29 22:56 UTC, styled-man commented on src/app/api/[trpc].ts
I don't think this file has any functionality

2024-03-29 22:56 UTC, styled-man commented on src/app/api/search.ts
I don't think this file has any functionality

2024-03-29 22:56 UTC, styled-man commented on src/Data/programData.ts
I don't think this file has any functionality

2024-03-29 22:56 UTC, styled-man commented on src/Data/page.tsx
I don't think this file has any functionality

2024-03-29 22:56 UTC, styled-man commented on src/app/jobs/DeleteModal.tsx
I don't think this file has any functionality

2024-03-29 22:56 UTC, styled-man commented on src/app/jobs/JobModal.tsx
I don't think this file has any functionality

2024-04-02 21:38 UTC, styled-man approved these changes

2024-04-02 22:07 UTC, styled-man approved these changes

2024-04-02 23:21 UTC, raidel-a submitted a review, later dismissed
Change events_tracker directory

2024-04-02 23:30 UTC, raidel-a approved these changes
lgtm

2024-04-02 23:32 UTC, styled-man approved these changes

2024-04-02 23:32 UTC, merged