Shareable components
INIT-Build-Web-Dev-3-Spring-2024/init-website pull request #17
Opened 2024-03-28 10:47 UTC by styled-man

2024-03-28 21:50 UTC, raidel-a approved these changes
Lgtm
Can we add the tailwind autosort class plugin??

2024-03-29 04:22 UTC, styled-man commented
> Lgtm Can we add the tailwind autosort class plugin??

That might get annoying for the people that use autosave

2024-03-29 12:11 UTC, raidel-a requested changes
animated gradient has visual bug onclick

2024-03-29 12:11 UTC, raidel-a commented on src/components/Button.tsx
> +    <GradientBorder
seeing a small visual bug on the button with gradientBorder where onclick the animated gradient translates -1 but the black mask does not.

2024-03-29 20:13 UTC, 02danieljonas requested changes

2024-03-29 20:13 UTC, 02danieljonas commented on src/components/Button.tsx
Modify the code so that the animated button can be set to always active, instead of active on hover.

2024-03-29 20:13 UTC, 02danieljonas commented on src/components/Button.tsx
Modify Link code so that a target can be set, i.e. target="_blank"

2024-03-29 20:15 UTC, 02danieljonas commented on src/components/Button.tsx
In cases where it is always active you can set the glow to be on hover and the border to be animated always

2024-03-29 20:19 UTC, 02danieljonas requested changes

2024-03-29 20:19 UTC, 02danieljonas commented on src/components/Button.tsx
Passing a classname of rounded-xl modifies the outside element but leaves the inner element alone.

2024-03-29 22:14 UTC, raidel-a approved these changes
LGTM

2024-03-29 22:22 UTC, 02danieljonas approved these changes
LGTM!!

2024-03-29 22:23 UTC, raidel-a approved these changes
LGT Daniel

2024-03-29 22:23 UTC, merged